on:
  push:
    branches:
      - master
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]
name: Check linting and tests
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run lint
    - name: Run tests
      run: yarn run test
